repos:
  - repo: local
    hooks:
      - id: pytest-generated
        name: python scripts (create pdf)
        entry: uv run pytest -q src/tests/test_pdf_scripts.py
        language: system
        pass_filenames: false
        stages: [pre-push]
        files: \.(py|yaml|json|html|css|js|yml|conf)$

      - id: pytest-endpoints-admin
        name: endpoints (admin)
        entry: uv run pytest -q src/tests/test_endpoints_admin.py
        language: system
        pass_filenames: false
        stages: [pre-push]
        files: \.(py|yaml|json|html|css|js|yml|conf)$

      - id: pytest-endpoints-auth-pages
        name: endpoints (auth pages)
        entry: uv run pytest -q src/tests/test_endpoints_auth_pages.py
        language: system
        pass_filenames: false
        stages: [pre-push]
        files: \.(py|yaml|json|html|css|js|yml|conf)$