services:
  backend:
    container_name: fastapi_app_dev
    env_file: .env.dev
    ports:
      - "8000:8000" # Host 8000 -> Container 8000

  mongo:
    container_name: mongo_db_dev
    env_file: .env.dev
    ports:
      - "27017:27017" # Host 27017 -> Container 27017

  nginx:
    container_name: nginx_proxy_dev
    ports:
      - "8080:80"  # Map local HTTP port to host 8080
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - ./src/web/static:/app/static:ro
      - ./src/web/templates:/app/templates:ro
    depends_on:
      - backend

  certbot:
    container_name: certbot_dev_disabled
    scale: 0